package com.travel.config.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing a single configuration entry in the centralised store.
 * <p>
 * Entries are uniquely identified by the triplet ({@code serviceId},
 * {@code namespace}, {@code configKey}), enforced by both the database
 * {@code UNIQUE} constraint and the named constraint below.
 * <p>
 * Optimistic locking is provided by the {@code @Version} field to prevent
 * lost-update races when multiple service instances modify the same key
 * concurrently.
 */
@Entity
@Table(
        name = "config_entries",
        uniqueConstraints = @UniqueConstraint(
                name = "uq_config_entry",
                columnNames = {"service_id", "namespace", "config_key"}
        )
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "configValue")   // avoid leaking potentially sensitive values in logs
public class ConfigEntry {

    /** Surrogate primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Logical identifier of the owning service (e.g. {@code "itinerary-impl"},
     * {@code "geo-service"}). Used as the first partitioning dimension.
     */
    @Column(name = "service_id", length = 100, nullable = false)
    private String serviceId;

    /**
     * Logical namespace within a service (e.g. {@code "default"},
     * {@code "feature-flags"}, {@code "secrets"}). Defaults to {@code "default"}.
     */
    @Column(name = "namespace", length = 100, nullable = false)
    @Builder.Default
    private String namespace = "default";

    /**
     * The configuration key within the given service + namespace scope.
     * Must be unique per (serviceId, namespace) pair.
     */
    @Column(name = "config_key", length = 255, nullable = false)
    private String configKey;

    /**
     * The configuration value, stored as plain text. May be {@code null} to
     * represent an explicitly unset key.
     */
    @Column(name = "config_value", columnDefinition = "TEXT")
    private String configValue;

    /**
     * JPA optimistic-locking version counter. Incremented on every update.
     * Starting value is {@code 0} (set by the database default).
     */
    @Version
    @Column(name = "version", nullable = false)
    @Builder.Default
    private long version = 0L;

    /**
     * {@code true} when {@link #configValue} is stored in encrypted form.
     * Decryption is the caller's responsibility.
     */
    @Column(name = "encrypted", nullable = false)
    @Builder.Default
    private boolean encrypted = false;

    /** Timestamp at which this entry was first persisted. Immutable after creation. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false,
            columnDefinition = "TIMESTAMPTZ")
    private OffsetDateTime createdAt;

    /** Timestamp of the last modification; updated automatically on every flush. */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false,
            columnDefinition = "TIMESTAMPTZ")
    private OffsetDateTime updatedAt;
}
