package com.travel.messaging;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity that represents a single entry in the transactional outbox table.
 *
 * <p>The outbox pattern guarantees at-least-once delivery: domain events are
 * written to {@code outbox_events} in the same ACID transaction as the
 * business operation, and a background scheduler ({@link OutboxPublisher})
 * relays them to Kafka once the transaction has committed.
 *
 * <h3>Schema notes</h3>
 * <ul>
 *   <li>{@code payload} is stored as {@code TEXT} in SQL terms; PostgreSQL
 *       columns can be cast to {@code JSONB} via a migration script if rich
 *       querying is needed.</li>
 *   <li>An index on {@code (published, created_at)} ensures the polling query
 *       in {@link OutboxRepository} remains efficient even as the table grows.</li>
 * </ul>
 */
@Entity
@Table(
        name = "outbox_events",
        indexes = {
                @Index(name = "idx_outbox_unpublished",
                        columnList = "published, created_at"),
                @Index(name = "idx_outbox_aggregate",
                        columnList = "aggregate_type, aggregate_id")
        }
)
public class OutboxEvent {

    // ── Identity ─────────────────────────────────────────────────────────────

    /**
     * Surrogate primary key – a UUID generated by the JVM so that the value is
     * known before the row is flushed to the database (useful for idempotency
     * tokens forwarded to Kafka message headers).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ── Aggregate context ─────────────────────────────────────────────────────

    /**
     * Logical type of the aggregate that produced this event
     * (e.g. {@code "Itinerary"}, {@code "Booking"}).
     * Used to derive the Kafka topic name in {@link OutboxPublisher}.
     */
    @Column(name = "aggregate_type", nullable = false, length = 128)
    private String aggregateType;

    /**
     * Identity of the aggregate instance that raised the event.
     */
    @Column(name = "aggregate_id", nullable = false)
    private UUID aggregateId;

    // ── Event metadata ────────────────────────────────────────────────────────

    /**
     * Fully-qualified event type name
     * (e.g. {@code "com.travel.itinerary.ItineraryCreatedEvent"}).
     * Forwarded as a Kafka record header ({@code X-Event-Type}) so that
     * consumers can route without deserialising the payload.
     */
    @Column(name = "event_type", nullable = false, length = 256)
    private String eventType;

    /**
     * JSON-serialised event payload produced by {@link OutboxEventPublisher}.
     * Stored as {@code TEXT} / {@code JSONB} depending on the DDL.
     */
    @Column(name = "payload", nullable = false, columnDefinition = "TEXT")
    private String payload;

    /**
     * Optional correlation identifier that can be used to trace a logical
     * request across service boundaries.  Populated from the
     * {@code X-Correlation-Id} HTTP header by {@link CorrelationIdFilter}.
     */
    @Column(name = "correlation_id", length = 64)
    private String correlationId;

    // ── Publication state ─────────────────────────────────────────────────────

    /**
     * {@code false} while the event has not yet been forwarded to Kafka;
     * set to {@code true} by {@link OutboxPublisher} after a successful send.
     */
    @Column(name = "published", nullable = false)
    private boolean published = false;

    // ── Timestamps ────────────────────────────────────────────────────────────

    /**
     * UTC instant at which the outbox row was inserted.
     * Set automatically by the {@link PrePersist} callback; never updated.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * UTC instant at which the event was successfully published to Kafka.
     * {@code null} until {@link OutboxPublisher} marks the event as delivered.
     */
    @Column(name = "published_at")
    private Instant publishedAt;

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    @PrePersist
    void onPrePersist() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
    }

    // ── Getters & setters ─────────────────────────────────────────────────────

    public UUID getId() {
        return id;
    }

    // id is generated – no public setter

    public String getAggregateType() {
        return aggregateType;
    }

    public void setAggregateType(String aggregateType) {
        this.aggregateType = aggregateType;
    }

    public UUID getAggregateId() {
        return aggregateId;
    }

    public void setAggregateId(UUID aggregateId) {
        this.aggregateId = aggregateId;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getPayload() {
        return payload;
    }

    public void setPayload(String payload) {
        this.payload = payload;
    }

    public String getCorrelationId() {
        return correlationId;
    }

    public void setCorrelationId(String correlationId) {
        this.correlationId = correlationId;
    }

    public boolean isPublished() {
        return published;
    }

    public void setPublished(boolean published) {
        this.published = published;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    // createdAt is set by @PrePersist – no public setter

    public Instant getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(Instant publishedAt) {
        this.publishedAt = publishedAt;
    }

    // ── Object overrides ──────────────────────────────────────────────────────

    @Override
    public String toString() {
        return "OutboxEvent{"
                + "id=" + id
                + ", aggregateType='" + aggregateType + '\''
                + ", aggregateId=" + aggregateId
                + ", eventType='" + eventType + '\''
                + ", correlationId='" + correlationId + '\''
                + ", published=" + published
                + ", createdAt=" + createdAt
                + '}';
    }
}
